const cars=[
{ref:'CC001',brand:'Mazda',line:'2',version:'Grand Touring LX',year:2024,box:'Automática',km:45000,motor:1500,price:77500000,image:'assets/mazda-frente.jpg',gallery:'assets/mazda-lateral.jpg'},
{ref:'CC003',brand:'Chevrolet',line:'Joy',version:'',year:2023,box:'Mecánica',km:39000,motor:1400,price:47500000,image:'assets/joy.jpg'},
{ref:'CC002',brand:'Kia',line:'Picanto',version:'Emotion',year:2018,box:'Mecánica',km:135000,motor:1000,price:42900000},
{ref:'CC004',brand:'Kia',line:'Picanto',version:'Zenith',year:2020,box:'Mecánica',km:85000,motor:1250,price:46900000},
{ref:'CC005',brand:'Subaru',line:'Forester',version:'Premium 4x4',year:2017,box:'Automática',km:106000,motor:2000,price:78900000},
{ref:'CC006',brand:'Kia',line:'Sportage',version:'Desire',year:2019,box:'Automática',km:78000,motor:2000,price:89500000},
{ref:'CC007',brand:'Suzuki',line:'Grand Vitara',version:'Híbrida',year:2024,box:'Automática',km:12000,motor:1500,price:108900000},
{ref:'CC008',brand:'Mazda',line:'CX-5',version:'Touring',year:2019,box:'Automática',km:85000,motor:2500,price:90900000},
{ref:'CC009',brand:'Audi',line:'Q3 Sportback',version:'',year:2024,box:'Automática',km:38000,motor:2000,price:124900000},
{ref:'CC010',brand:'Mazda',line:'CX-30',version:'Grand Touring LX híbrida',year:2025,box:'Automática',km:45000,motor:2000,price:118900000},
{ref:'CC011',brand:'Chevrolet',line:'Tracker',version:'Turbo LS',year:2021,box:'Mecánica',km:36000,motor:1200,price:61900000}
];
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n),num=n=>new Intl.NumberFormat('es-CO').format(n);let mode='car';
function renderCars(){const q=$('#search').value.toLowerCase(),box=$('#transmission').value,price=Number($('#price').value)||Infinity;const filtered=cars.filter(c=>(`${c.brand} ${c.line} ${c.ref}`.toLowerCase().includes(q))&&(!box||c.box===box)&&c.price<=price);$('#result-count').textContent=`${filtered.length} vehículos`;$('#cars').innerHTML=filtered.length?filtered.map(c=>`<article class="car-card"><div class="car-photo">${c.image?`<img src="${c.image}" loading="lazy" alt="${c.brand} ${c.line}, fotografía real del vehículo">`:`<div class="no-photo"><strong>${c.brand.toUpperCase()}</strong><span>Fotografías por validar</span></div>`}<span class="ref">${c.ref}</span></div><div class="car-body"><span class="tag">Información por confirmar</span><h3>${c.brand} ${c.line}</h3><div class="variant">${c.version||'Versión por confirmar'}</div><div class="specs"><span>${c.year}</span><span>${num(c.km)} km</span><span>${c.box}</span></div><div class="card-bottom"><strong>${money(c.price)}</strong><button data-car="${c.ref}">Ver ficha</button></div></div></article>`).join(''):'<p>No hay vehículos que coincidan. Prueba otros filtros.</p>';}
function switchMode(next){mode=next;document.body.classList.toggle('paint-mode',next==='paint');document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===next;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('#panel-car').hidden=next!=='car';$('#panel-paint').hidden=next!=='paint';$('#hero-label').textContent=next==='car'?'01 / CELESCAR · CALI':'02 / CELESPAINT · CALI';$('#hero-title').innerHTML=next==='car'?'Tu próximo<br>capítulo empieza<br><em>al volante.</em>':'Una nueva vida.<br>El mismo carro.<br><em>Tu esencia.</em>';$('#hero-description').textContent=next==='car'?'Explora los vehículos de nuestro portafolio. Conoce cada detalle y conversa con el equipo antes de decidir.':'Tu carro merece una segunda oportunidad. Proyectamos un portafolio de cuidado y reparación con información clara en cada paso.';$('#hero-action').textContent=next==='car'?'Explorar vehículos':'Explorar servicios';$('#hero-note').textContent=next==='car'?'Fotografías reales · Atención cercana':'Valoración · Trabajo · Entrega';$('#section-title').textContent=next==='car'?'Encuentra el que va contigo.':'El cuidado está en los detalles.';$('#section-description').innerHTML=next==='car'?'Una primera muestra de nuestro inventario.<br>Confirma precio y disponibilidad con el equipo.':'Propuesta inicial de servicios.<br>Alcances y tarifas pendientes de validación.';$('#hero').classList.remove('mode-enter');void $('#hero').offsetWidth;$('#hero').classList.add('mode-enter');history.replaceState(null,'',`#${next==='car'?'celescar':'celespaint'}`);}
function renderHistory(type){document.querySelectorAll('[data-history]').forEach(b=>{b.classList.toggle('active',b.dataset.history===type);b.setAttribute('aria-pressed',b.dataset.history===type)});$('#history-content').innerHTML=`<div><span class="empty-label">ARCHIVO ${type==='ventas'?'CELESCAR':'CELESPAINT'}</span><h3>${type==='ventas'?'Cada entrega, una historia.':'El antes. El proceso. El resultado.'}</h3><p>${type==='ventas'?'Aquí reuniremos vehículos entregados con su referencia, fecha y fotografías autorizadas.':'Aquí reuniremos trabajos terminados, fotografías del proceso y su alcance real.'}</p><span class="tag">Aún no hay casos históricos validados</span></div><div class="record-fields">${(type==='ventas'?['Referencia del vehículo','Fecha de entrega','Galería autorizada','Historia de la entrega']:['Referencia del trabajo','Servicio realizado','Antes y después','Fecha de entrega']).map(s=>`<span>${s}</span>`).join('')}</div>`;}
function showDetail(ref){const c=cars.find(x=>x.ref===ref);$('#detail-body').innerHTML=`<div class="eyebrow">CELESCAR / ${c.ref}</div>${c.image?`<img class="detail-img" src="${c.gallery||c.image}" alt="${c.brand} ${c.line}, foto real">`:''}<h2>${c.brand} ${c.line}</h2><p>${c.version} · ${money(c.price)}</p><div class="detail-specs"><span>Modelo: ${c.year}</span><span>Recorrido: ${num(c.km)} km</span><span>Caja: ${c.box}</span><span>Motor: ${num(c.motor)} cc</span></div><p class="detail-text">Datos recibidos el 4 de octubre de 2026. Precio, disponibilidad, estado y documentación pendientes de confirmación. Esta ficha de prueba no constituye una oferta verificada.</p><p class="detail-text">Consulta al equipo mencionando la referencia <b>${c.ref}</b>.</p><a class="primary" href="https://www.instagram.com/celes.group/" target="_blank" rel="noopener">Contactar por Instagram</a> <button class="ghost" id="share-car">Compartir ficha</button>`;$('#detail').showModal();$('#share-car').onclick=()=>share(`${c.brand} ${c.line} · ${c.ref} · CELESGROUP`,`${location.origin}${location.pathname}#vehiculo-${ref}`);}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}async function share(title='CELESGROUP · Portafolio de prueba',url=location.href){try{if(navigator.share)await navigator.share({title,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);toast('Enlace copiado para compartir')}else toast('Copia la dirección de esta página para compartir')}catch(e){if(e.name!=='AbortError')toast('Puedes copiar el enlace desde la barra de dirección')}}
document.querySelectorAll('[data-mode]').forEach(b=>{b.onclick=()=>switchMode(b.dataset.mode);b.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=mode==='car'?'paint':'car';switchMode(next);$(`#tab-${next}`).focus()}}});['search','transmission','price'].forEach(id=>$(`#${id}`).addEventListener(id==='search'?'input':'change',renderCars));$('#cars').onclick=e=>{const b=e.target.closest('[data-car]');if(b)showDetail(b.dataset.car)};document.querySelectorAll('.share').forEach(b=>b.onclick=()=>share());document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>renderHistory(b.dataset.history));$('.close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{$('#detail-body').innerHTML=`<div class="eyebrow">CELESPAINT / PORTAFOLIO PROPUESTO</div><h2>${b.dataset.service}</h2><p class="detail-text">Primero se valora el vehículo; luego se define el alcance, el precio y el tiempo. Este servicio está presentado como propuesta y requiere confirmación del responsable del taller.</p><p class="detail-text">Las evidencias de trabajos reales se incorporarán al histórico cuando estén validadas y autorizadas.</p><a class="primary" href="https://www.instagram.com/celes.group/" target="_blank" rel="noopener">Conocer al equipo</a>`;$('#detail').showModal()});renderCars();renderHistory('ventas');if(location.hash==='#celespaint')switchMode('paint');if(location.hash.startsWith('#vehiculo-')){const ref=location.hash.replace('#vehiculo-','');if(cars.some(c=>c.ref===ref))showDetail(ref)}
