const photos=(ref,order=[1,2,3,4,5])=>order.map(i=>`assets/cars/${ref.toLowerCase()}-${String(i).padStart(2,'0')}.webp`);
const cars=[
{ref:'CC012',brand:'MINI',line:'Cooper',version:'',year:2011,box:'Mecánica',km:null,motor:null,price:null,gallery:['assets/cars/cc012-01.jpg','assets/cars/cc012-02.jpg','assets/cars/cc012-03.jpg','assets/cars/cc012-04.jpg','assets/cars/cc012-05.jpg','assets/cars/cc012-06.jpg','assets/cars/cc012-07.jpg','assets/cars/cc012-08.jpg'],pitch:'Un MINI con identidad propia: diseño clásico, techo negro, gráficos laterales de inspiración británica e interior azul que lo hacen difícil de pasar por alto. Una opción para quien busca un compacto con estilo y mucha personalidad.'},
{ref:'CC001',brand:'Mazda',line:'2',version:'Grand Touring LX',year:2024,box:'Automática',km:45000,motor:1500,price:77500000,gallery:photos('CC001',[4,5,1,2,3]),pitch:'Versión Grand Touring LX, caja automática y un formato compacto para moverte con comodidad todos los días.'},
{ref:'CC003',brand:'Chevrolet',line:'Joy',version:'',year:2023,box:'Mecánica',km:39000,motor:1400,price:47500000,gallery:photos('CC003',[2,4,1,3,5]),pitch:'Modelo 2023 con caja mecánica: una opción práctica para quien prioriza sencillez y funcionalidad.'},
{ref:'CC002',brand:'Kia',line:'Picanto',version:'Emotion',year:2018,box:'Mecánica',km:135000,motor:1000,price:42900000,pitch:'Un compacto ágil y sencillo de usar, con caja mecánica y tamaño ideal para el ritmo urbano.'},
{ref:'CC004',brand:'Kia',line:'Picanto',version:'Zenith',year:2020,box:'Mecánica',km:85000,motor:1250,price:46900000,gallery:photos('CC004',[2,4,5,1,3]),pitch:'Picanto Zenith con motor 1.250 cc y caja mecánica: compacto, fácil de llevar y con personalidad.'},
{ref:'CC005',brand:'Subaru',line:'Forester',version:'Premium 4x4',year:2017,box:'Automática',km:106000,motor:2000,price:78900000,gallery:photos('CC005',[2,3,1,4,5]),pitch:'Forester Premium 4x4: espacio, tracción y versatilidad para quien busca una SUV preparada para distintos caminos.'},
{ref:'CC006',brand:'Kia',line:'Sportage',version:'Desire',year:2019,box:'Automática',km:78000,motor:2000,price:89500000,gallery:photos('CC006',[3,5,2,4,1]),pitch:'Sportage Desire automática: una SUV con buen espacio y una configuración cómoda para uso diario y viajes.'},
{ref:'CC007',brand:'Suzuki',line:'Grand Vitara',version:'Híbrida',year:2024,box:'Automática',km:12000,motor:1500,price:108900000,gallery:photos('CC007',[5,4,2,3,1]),pitch:'Grand Vitara híbrida 2024 y automática: una combinación moderna para quien quiere dar el salto a una SUV electrificada.'},
{ref:'CC008',brand:'Mazda',line:'CX-5',version:'Touring',year:2019,box:'Automática',km:85000,motor:2500,price:90900000,gallery:photos('CC008',[5,2,3,1,4]),pitch:'CX-5 Touring automática con motor 2.5 L: una SUV de diseño sobrio y configuración versátil para ciudad y carretera.'},
{ref:'CC009',brand:'Audi',line:'Q3 Sportback',version:'',year:2024,box:'Automática',km:38000,motor:2000,price:124900000,gallery:photos('CC009',[3,2,5,1,4]),pitch:'Q3 Sportback 2024: diseño deportivo, caja automática y una presencia claramente premium.'},
{ref:'CC010',brand:'Mazda',line:'CX-30',version:'Grand Touring LX híbrida',year:2025,box:'Automática',km:45000,motor:2000,price:118900000,pitch:'CX-30 Grand Touring LX híbrida: diseño Mazda, caja automática y tecnología híbrida en un formato SUV compacto.'},
{ref:'CC011',brand:'Chevrolet',line:'Tracker',version:'Turbo LS',year:2021,box:'Mecánica',km:36000,motor:1200,price:61900000,pitch:'Tracker Turbo LS: formato SUV, motor turbo y caja mecánica para quien busca una alternativa compacta con carácter.'}
];
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n),num=n=>new Intl.NumberFormat('es-CO').format(n);let mode='car';
const priceText=c=>Number.isFinite(c.price)?money(c.price):'Precio por confirmar';
const kmText=c=>Number.isFinite(c.km)?`${num(c.km)} km`:'Kilometraje por confirmar';
const motorText=c=>Number.isFinite(c.motor)?`${num(c.motor)} cc`:'Motor por confirmar';
function renderCars(){
 const q=$('#search').value.toLowerCase(),box=$('#transmission').value,limit=Number($('#price').value)||Infinity;
 const filtered=cars.filter(c=>(`${c.brand} ${c.line} ${c.version||''} ${c.year} ${c.ref}`.toLowerCase().includes(q))&&(!box||c.box===box)&&(limit===Infinity||(Number.isFinite(c.price)&&c.price<=limit)));
 $('#result-count').textContent=`${filtered.length} vehículos`;
 $('#cars').innerHTML=filtered.length?filtered.map(c=>{
  const gallery=c.gallery||[];
  const media=gallery.length?`<div class="card-gallery"><div class="card-media-track">${gallery.map((src,i)=>`<img src="${src}" loading="lazy" alt="${c.brand} ${c.line}, fotografía real ${i+1} de ${gallery.length}">`).join('')}</div>${gallery.length>1?`<button class="gallery-nav prev" data-gallery-prev aria-label="Fotografía anterior">‹</button><button class="gallery-nav next" data-gallery-next aria-label="Fotografía siguiente">›</button><div class="card-media-meta"><span>${gallery.length} fotos</span><span>Desliza ↔</span></div>`:''}</div>`:`<div class="no-photo"><strong>${c.brand.toUpperCase()}</strong><span>Fotografías pendientes</span></div>`;
  return `<article class="car-card" data-car="${c.ref}"><div class="car-photo">${media}<span class="ref">${c.ref}</span></div><div class="car-body"><span class="tag">${c.ref==='CC012'?'Nuevo ingreso':'Disponible'}</span><h3>${c.brand} ${c.line}</h3><div class="variant">${c.version||'Versión por confirmar'}</div><div class="specs"><span>${c.year}</span><span>${kmText(c)}</span><span>${c.box||'Caja por confirmar'}</span></div><p class="card-pitch">${c.pitch}</p><div class="card-bottom"><strong class="${Number.isFinite(c.price)?'':'price-pending'}">${priceText(c)}</strong><button class="card-cta" data-open-car>Ver ficha <span>→</span></button></div></div></article>`;
 }).join(''):'<p>No hay vehículos que coincidan. Prueba otros filtros.</p>';
}
function switchMode(next){mode=next;document.body.classList.toggle('paint-mode',next==='paint');document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===next;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('#panel-car').hidden=next!=='car';$('#panel-paint').hidden=next!=='paint';$('#hero-label').textContent=next==='car'?'01 / CELESCAR · CALI':'02 / CELESPAINT · CALI';$('#hero-title').innerHTML=next==='car'?'Tu próximo<br>capítulo empieza<br><em>al volante.</em>':'Una nueva vida.<br>El mismo carro.<br><em>Tu esencia.</em>';$('#hero-description').textContent=next==='car'?'Explora los vehículos de nuestro portafolio. Conoce cada detalle y conversa con el equipo antes de decidir.':'Tu carro merece una segunda oportunidad. Proyectamos un portafolio de cuidado y reparación con información clara en cada paso.';$('#hero-action').textContent=next==='car'?'Explorar vehículos':'Explorar servicios';$('#hero-note').textContent=next==='car'?'Fotografías reales · Atención cercana':'Valoración · Trabajo · Entrega';$('#hero-media').src=next==='car'?'assets/cars/cc012-01.jpg':'assets/porcelanizado-poster.webp?v=3';$('#hero-media').alt=next==='car'?'MINI Cooper blanco 2011 fotografiado en las instalaciones de CELESGROUP':'Vehículo rojo después de restauración de pintura y porcelanizado CELESPAINT';$('#photo-label').textContent=next==='car'?'MINI COOPER · 2011':'RESTAURACIÓN + PORCELANIZADO';$('#photo-detail').textContent=next==='car'?'Nuevo ingreso · 8 fotografías reales':'Video real del portafolio CELESPAINT';$('#section-title').textContent=next==='car'?'Encuentra el que va contigo.':'El cuidado está en los detalles.';$('#section-description').innerHTML=next==='car'?'Explora cada vehículo y desliza sus fotografías.<br>Haz clic en cualquier ficha para conocerlo mejor.':'Propuesta inicial de servicios.<br>Alcances y tarifas pendientes de validación.';$('#hero').classList.remove('mode-enter');void $('#hero').offsetWidth;$('#hero').classList.add('mode-enter');history.replaceState(null,'',`#${next==='car'?'celescar':'celespaint'}`);}
function renderHistory(type){document.querySelectorAll('[data-history]').forEach(b=>{b.classList.toggle('active',b.dataset.history===type);b.setAttribute('aria-pressed',b.dataset.history===type)});$('#history-content').innerHTML=`<div><span class="empty-label">ARCHIVO ${type==='ventas'?'CELESCAR':'CELESPAINT'}</span><h3>${type==='ventas'?'Cada entrega, una historia.':'El antes. El proceso. El resultado.'}</h3><p>${type==='ventas'?'Aquí reuniremos vehículos entregados con su referencia, fecha y fotografías autorizadas.':'Aquí reuniremos trabajos terminados, fotografías del proceso y su alcance real.'}</p><span class="tag">Aún no hay casos históricos validados</span></div><div class="record-fields">${(type==='ventas'?['Referencia del vehículo','Fecha de entrega','Galería autorizada','Historia de la entrega']:['Referencia del trabajo','Servicio realizado','Antes y después','Fecha de entrega']).map(s=>`<span>${s}</span>`).join('')}</div>`;}
function showDetail(ref){
 const c=cars.find(x=>x.ref===ref);if(!c)return;
 const gallery=c.gallery||[];
 $('#detail-body').innerHTML=`<div class="eyebrow">CELESCAR / ${c.ref}</div>${gallery.length?`<div class="detail-gallery"><img id="detail-main" class="detail-img" src="${gallery[0]}" alt="${c.brand} ${c.line}, foto real 1 de ${gallery.length}"><div class="detail-thumbs">${gallery.map((src,i)=>`<button class="${i===0?'active':''}" data-photo="${src}" data-alt="${c.brand} ${c.line}, foto real ${i+1} de ${gallery.length}" aria-label="Ver foto ${i+1}"><img src="${src}" alt="" loading="lazy"></button>`).join('')}</div></div>`:'<div class="detail-empty">Fotografías pendientes de cargar</div>'}<div class="detail-title-row"><div><h2>${c.brand} ${c.line}</h2><p>${c.version||'Versión por confirmar'}</p></div><strong>${priceText(c)}</strong></div><p class="detail-lead">${c.pitch}</p><div class="detail-specs"><span>Modelo: ${c.year}</span><span>Recorrido: ${kmText(c)}</span><span>Caja: ${c.box||'Por confirmar'}</span><span>Motor: ${motorText(c)}</span></div><p class="detail-text">Fotografías reales del vehículo. Precio, disponibilidad, documentación y cualquier dato marcado como “por confirmar” deben validarse con el equipo antes de tomar una decisión.</p><p class="detail-text">Consulta al equipo mencionando la referencia <b>${c.ref}</b>.</p><div class="detail-actions"><a class="primary" href="https://www.instagram.com/celes.group/" target="_blank" rel="noopener">Quiero saber más</a><button class="ghost" id="share-car">Compartir ficha</button></div>`;
 $('#detail').showModal();
 document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const main=$('#detail-main');main.src=b.dataset.photo;main.alt=b.dataset.alt;document.querySelectorAll('[data-photo]').forEach(x=>x.classList.toggle('active',x===b))});
 $('#share-car').onclick=()=>share(`${c.brand} ${c.line} · ${c.ref} · CELESGROUP`,`${location.origin}${location.pathname}#vehiculo-${ref}`);
}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}async function share(title='CELESGROUP · Portafolio de prueba',url=location.href){try{if(navigator.share)await navigator.share({title,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);toast('Enlace copiado para compartir')}else toast('Copia la dirección de esta página para compartir')}catch(e){if(e.name!=='AbortError')toast('Puedes copiar el enlace desde la barra de dirección')}}
document.querySelectorAll('[data-mode]').forEach(b=>{b.onclick=()=>switchMode(b.dataset.mode);b.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=mode==='car'?'paint':'car';switchMode(next);$(`#tab-${next}`).focus()}}});['search','transmission','price'].forEach(id=>$(`#${id}`).addEventListener(id==='search'?'input':'change',renderCars));let dragX=0,dragY=0,suppressCardClick=false;
$('#cars').addEventListener('pointerdown',e=>{dragX=e.clientX;dragY=e.clientY;suppressCardClick=false});
$('#cars').addEventListener('pointerup',e=>{suppressCardClick=Math.hypot(e.clientX-dragX,e.clientY-dragY)>10;setTimeout(()=>suppressCardClick=false,0)});
$('#cars').onclick=e=>{const nav=e.target.closest('[data-gallery-prev],[data-gallery-next]');if(nav){const track=nav.closest('.car-photo').querySelector('.card-media-track');track.scrollBy({left:(nav.hasAttribute('data-gallery-next')?1:-1)*track.clientWidth,behavior:'smooth'});return}const card=e.target.closest('.car-card[data-car]');if(card&&!suppressCardClick)showDetail(card.dataset.car)};document.querySelectorAll('.share').forEach(b=>b.onclick=()=>share());document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>renderHistory(b.dataset.history));$('.close').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{$('#detail-body').innerHTML=`<div class="eyebrow">CELESPAINT / PORTAFOLIO PROPUESTO</div><h2>${b.dataset.service}</h2><p class="detail-text">Primero se valora el vehículo; luego se define el alcance, el precio y el tiempo. Este servicio está presentado como propuesta y requiere confirmación del responsable del taller.</p><p class="detail-text">Las evidencias de trabajos reales se incorporarán al histórico cuando estén validadas y autorizadas.</p><a class="primary" href="https://www.instagram.com/celes.group/" target="_blank" rel="noopener">Conocer al equipo</a>`;$('#detail').showModal()});renderCars();renderHistory('ventas');if(location.hash==='#celespaint')switchMode('paint');if(location.hash.startsWith('#vehiculo-')){const ref=location.hash.replace('#vehiculo-','');if(cars.some(c=>c.ref===ref))showDetail(ref)}
